version: "3"
services:
  client:
    container_name: youtube-client
    image: node:13.7.0-alpine3.11
    ports:
      - "9000:3000"
    volumes:
      - ./youtube-client:/usr/src/app
    working_dir: /usr/src/app
    command: "npm start"
  server:
    container_name: youtube-server
    image: node:13.7.0-alpine3.11
    ports:
      - "9001:3000"
    volumes:
      - ./youtube-server:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run start:dev"
