version: "3"
services:
  client:
    container_name: youtube-client
    image: node:13.8.0-alpine3.11
    ports:
      - 9000:3000
    working_dir: /usr/src/app
    volumes:
      - ./youtube-client:/usr/src/app
    command: "npm start"
  server:
    container_name: youtube-server
    image: node:13.8.0-alpine3.11
    environment:
      - JWT_SECRET=verySecretPassword
    ports:
      - 9001:3000
    volumes:
      - ./youtube-server:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - database
    command: "npm run start:dev"
  database:
    container_name: youtube-database
    image: postgres:12.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: youtube
      POSTGRES_PASSWORD: youtube
      POSTGRES_DB: youtube
  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - 9002:8080
